import React, { useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import type { Collection, ContinueItem, Folder, LibraryStatus, RemoteCommand, Track } from '../shared/ipc'
import './style.css'

const fmt=(seconds:number|null)=>{if(seconds==null||!Number.isFinite(seconds))return '--:--';const s=Math.max(0,Math.floor(seconds));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
const coverUrl=(item:{cover:{kind:string|null;data:Record<string,unknown>|null;dominantColor:string|null}})=>{const c=item.cover;if(c.kind==='image'&&typeof c.data?.relativePath==='string')return `hb-cover://cover/${encodeURI(c.data.relativePath)}`;if(c.kind==='remote'&&typeof c.data?.url==='string')return c.data.url;return null}
function Cover({item,small=false}:{item:{cover:{kind:string|null;data:Record<string,unknown>|null;dominantColor:string|null}};small?:boolean}){const url=coverUrl(item);const color=item.cover.dominantColor||'#30343b';return url?<img className={small?'cover small':'cover'} src={url} style={{backgroundColor:color}}/>:<div className={small?'cover small placeholder':'cover placeholder'} style={{backgroundColor:color}}><span>🐻</span></div>}

type View='all'|'continue'|'favorites'|'search'
function App(){
 const [status,setStatus]=useState<LibraryStatus|null>(null),[folders,setFolders]=useState<Folder[]>([]),[collections,setCollections]=useState<Collection[]>([]),[view,setView]=useState<View>('all'),[folderId,setFolderId]=useState<string|null>(null),[selected,setSelected]=useState<Collection|null>(null),[tracks,setTracks]=useState<Track[]>([]),[continueItems,setContinueItems]=useState<ContinueItem[]>([]),[favoriteItems,setFavoriteItems]=useState<Track[]>([]),[query,setQuery]=useState(''),[results,setResults]=useState<Track[]>([]),[text,setText]=useState<string|null>(null),[current,setCurrent]=useState<Track|null>(null),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[error,setError]=useState(''),[baidu,setBaidu]=useState({configured:false,connected:false,expiresAt:null as number|null}),[queue,setQueue]=useState<Track[]>([]),[volume,setVolume]=useState(1)
 const audio=useRef<HTMLAudioElement>(null)
 const load=async()=>{try{const [s,f,c,cont,b]=await Promise.all([window.api.libraryGetStatus(),window.api.libraryGetFolders(),window.api.libraryGetCollections(folderId),window.api.libraryGetContinue(20),window.api.baiduGetStatus()]);setStatus(s);setFolders(f);setCollections(c);setContinueItems(cont);setBaidu(b)}catch(e){setError(String(e))}}
 useEffect(()=>{void load()},[folderId])
 useEffect(()=>{if(!selected)return;window.api.libraryGetTracks(selected.id,0,300).then(p=>setTracks(p.tracks)).catch(e=>setError(String(e)))},[selected])
 useEffect(()=>{if(view==='favorites')window.api.libraryGetFavorites().then(setFavoriteItems).catch(e=>setError(String(e)));},[view])
 const play=async(track:Track)=>{if(track.locationType==='text'){setText(await window.api.trackGetTextContent(track.id));return}if(!track.playable){setError('此曲目仅在 iOS 设备上可用，桌面暂不支持。');return}setCurrent(track);setPlaying(true);setError('')}
 const playTrackAt=(list:Track[],i:number)=>{if(list[i]){setQueue(list);void play(list[i])}}
 const nextTrack=()=>{const q=queue.length?queue:tracks;const i=q.findIndex(t=>t.id===current?.id);if(i>=0&&i+1<q.length)playTrackAt(q,i+1)}
 const prevTrack=()=>{const q=queue.length?queue:tracks;const i=q.findIndex(t=>t.id===current?.id);if(i>0)playTrackAt(q,i-1)}
 const remoteCommandHandler=useRef<(c:RemoteCommand)=>void>(()=>{})
 remoteCommandHandler.current=(command)=>{switch(command.action){
  case 'play': if(command.tracks.length)playTrackAt(command.tracks,0); break
  case 'playSingle': playTrackAt([command.track],0); break
  case 'next': nextTrack(); break
  case 'prev': prevTrack(); break
  case 'togglePlay': { if(audio.current){ if(audio.current.paused)void audio.current.play(); else audio.current.pause() } break }
  case 'pause': audio.current?.pause(); break
  case 'resume': void audio.current?.play(); break
  case 'setVolume': { const v=Math.min(1,Math.max(0,command.volume)); setVolume(v); if(audio.current)audio.current.volume=v; break }
  case 'seek': { if(audio.current)audio.current.currentTime=command.positionSec; break }
 } if(command.id)void window.api.ackRemoteCommand(command.id)}
 useEffect(()=>window.api.onRemoteCommand(c=>remoteCommandHandler.current(c)),[])
 useEffect(()=>{const el=audio.current;if(!el)return; if(current){el.src=`hb-media://track/${current.id}`;el.playbackRate=speed;const p=current.playback?.position||0;const onMeta=()=>{if(p>0&&p<el.duration-2)el.currentTime=p;void el.play().catch(()=>setError('无法播放：请检查网络或百度网盘登录状态。'))};el.addEventListener('loadedmetadata',onMeta,{once:true});el.onerror=()=>setError(current.locationType==='baidu'?'百度曲目需要先登录百度网盘。':'播放失败，请检查网络。');return()=>el.removeEventListener('loadedmetadata',onMeta)}},[current])
 useEffect(()=>{if(audio.current)audio.current.playbackRate=speed},[speed])
 useEffect(()=>{if(audio.current)audio.current.volume=volume},[volume])
 useEffect(()=>{const push=()=>{const el=audio.current;void window.api.pushPlaybackState({isPlaying:playing,currentTrack:current,queueLength:queue.length,currentIndex:current?queue.findIndex(t=>t.id===current.id):-1,volume,positionSec:el?.currentTime??0,durationSec:el?.duration||current?.duration||0})};push();const id=setInterval(push,1000);return()=>clearInterval(id)},[playing,current,queue,volume])
 const displayed=useMemo(()=>view==='continue'?continueItems:view==='favorites'?favoriteItems:results,[view,continueItems,favoriteItems,results])
 const search=async()=>{if(!query.trim())return;setView('search');setResults(await window.api.librarySearch(query,100))}
 const refresh=async()=>{const s=await window.api.libraryRefresh();setStatus(s);if(s.dbReady){setCollections(await window.api.libraryGetCollections(folderId));setError('')}}
 return <div className="app"><aside><div className="brand"><span className="brand-mark">🐻‍❄️</span><div>PolarBear<small>DESKTOP</small></div></div><nav><button className={view==='all'&&!folderId?'active':''} onClick={()=>{setFolderId(null);setView('all');setSelected(null)}}>▦ <span>全部合集</span></button><button className={view==='continue'?'active':''} onClick={()=>setView('continue')}>◷ <span>继续收听</span></button><button className={view==='favorites'?'active':''} onClick={()=>setView('favorites')}>★ <span>收藏曲目</span></button></nav><div className="folders"><label>文件夹</label>{folders.map(f=><button key={f.id} className={folderId===f.id?'folder active':''} onClick={()=>{setFolderId(f.id);setView('all');setSelected(null)}}><span className="folder-dot"/> {f.name}</button>)}</div><div className="sidebar-foot"><button onClick={refresh}>↻ 刷新库</button><span className="readonly">只读模式 · 不会修改 iOS 数据</span></div></aside><main><header><div className="search"><span>⌕</span><input value={query} placeholder="搜索合集、作者或曲目" onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void search()}/>{query&&<button onClick={()=>{setQuery('');setView('all')}}>×</button>}</div><button className="settings" onClick={async()=>{const next=baidu.connected?await window.api.baiduLogout():await window.api.baiduLogin();setBaidu(next)}}>{baidu.connected?'百度已登录':'百度网盘登录'}</button></header>{error&&<div className="notice">{error}<button onClick={()=>setError('')}>×</button></div>}{!status?.dbReady?<Empty status={status} onRefresh={refresh}/>:view==='all'&&!selected?<><div className="heading"><div><h1>{folderId?folders.find(f=>f.id===folderId)?.name:'我的书库'}</h1><p>{collections.length} 个合集 · {status.tracks.toLocaleString()} 个曲目</p></div></div><div className="grid">{collections.map(c=><CollectionCard key={c.id} item={c} onClick={()=>setSelected(c)}/>)}</div></>:selected?<Detail collection={selected} tracks={tracks} onBack={()=>setSelected(null)} onPlay={play}/>:<TrackView title={view==='continue'?'继续收听':view==='favorites'?'收藏曲目':'搜索结果'} tracks={displayed} onPlay={play}/>}</main><Player track={current} playing={playing} setPlaying={setPlaying} audio={audio} speed={speed} setSpeed={setSpeed} onNext={nextTrack} onPrev={prevTrack}/><audio ref={audio} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>{setPlaying(false)}}/> {text!==null&&<div className="modal" onClick={()=>setText(null)}><article onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setText(null)}>×</button><pre>{text}</pre></article></div>}</div>
}
function Empty({status,onRefresh}:{status:LibraryStatus|null;onRefresh:()=>void}){return <div className="empty"><div className="empty-bear">🐻‍❄️</div><h2>还没有找到 PolarBear 音频库</h2><p>{status?.error||'请在 iOS 端开启 iCloud 同步，然后点击刷新库。'}</p><button onClick={onRefresh}>刷新库</button></div>}
function CollectionCard({item,onClick}:{item:Collection;onClick:()=>void}){return <button className="card" onClick={onClick}><Cover item={item}/><div className="card-body"><h3>{item.title}</h3><p>{item.author||'未知作者'}</p><div className="meta"><span>{item.trackCount} 曲目</span>{item.progress>0&&<span>{Math.round(item.progress*100)}%</span>}</div>{item.progress>0&&<div className="progress"><i style={{width:`${item.progress*100}%`}}/></div>}</div></button>}
function Detail({collection,tracks,onBack,onPlay}:{collection:Collection;tracks:Track[];onBack:()=>void;onPlay:(t:Track)=>void}){return <><div className="detail-head"><button className="back" onClick={onBack}>‹ 返回</button><div className="detail-cover"><Cover item={collection} small/></div><div><h1>{collection.title}</h1><p>{collection.author||'未知作者'} · {tracks.length}/{collection.trackCount} 曲目</p><p className="description">{collection.description}</p></div></div><div className="track-list">{tracks.map((t,i)=><TrackRow key={t.id} track={t} index={i+1} onPlay={onPlay}/>)}</div></>}
function TrackView({title,tracks,onPlay}:{title:string;tracks:Track[];onPlay:(t:Track)=>void}){return <><div className="heading"><h1>{title}</h1><p>{tracks.length} 个结果</p></div><div className="track-list">{tracks.map((t,i)=><TrackRow key={t.id} track={t} index={i+1} onPlay={onPlay}/>)}</div></>}
function TrackRow({track,index,onPlay}:{track:Track;index:number;onPlay:(t:Track)=>void}){const pct=track.playback&&track.playback.duration?Math.min(100,track.playback.position/track.playback.duration*100):0;return <div className={`track-row ${!track.playable?'disabled':''}`}><span className="track-num">{index}</span><button className="play-btn" onClick={()=>onPlay(track)}>{track.locationType==='text'?'▤':'▶'}</button><div className="track-info"><strong>{track.displayName}</strong><small>{track.chapter||track.locationType}</small>{pct>0&&<div className="progress"><i style={{width:`${pct}%`}}/></div>}</div><span className="track-duration">{fmt(track.duration)}</span><span className="favorite">{track.isFavorite?'★':'☆'}</span></div>}
function Player({track,playing,setPlaying,audio,speed,setSpeed,onNext,onPrev}:{track:Track|null;playing:boolean;setPlaying:(v:boolean)=>void;audio:React.RefObject<HTMLAudioElement>;speed:number;setSpeed:(n:number)=>void;onNext:()=>void;onPrev:()=>void}){const [pos,setPos]=useState(0),[duration,setDuration]=useState(0);useEffect(()=>{const el=audio.current;if(!el)return;const update=()=>{setPos(el.currentTime);setDuration(el.duration||track?.duration||0)};el.addEventListener('timeupdate',update);el.addEventListener('loadedmetadata',update);return()=>{el.removeEventListener('timeupdate',update);el.removeEventListener('loadedmetadata',update)}},[audio,track]);return <div className="player"><div className="now"><div className="mini-cover">🐻</div><div><b>{track?.displayName||'选择一首曲目开始播放'}</b><small>{track?'正在播放':'HappyBear Desktop'}</small></div></div><div className="controls"><div className="buttons"><button onClick={onPrev} disabled={!track}>⏮</button><button className="main-play" onClick={()=>{if(!track)return;if(playing){audio.current?.pause();setPlaying(false)}else{void audio.current?.play();setPlaying(true)}}} disabled={!track}>{playing?'Ⅱ':'▶'}</button><button onClick={onNext} disabled={!track}>⏭</button></div><div className="timeline"><span>{fmt(pos)}</span><input type="range" min="0" max={duration||1} step="0.1" value={Math.min(pos,duration||1)} onChange={e=>{const v=Number(e.target.value);if(audio.current)audio.current.currentTime=v;setPos(v)}}/><span>{fmt(duration)}</span></div></div><select value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value="0.8">0.8×</option><option value="1">1×</option><option value="1.25">1.25×</option><option value="1.5">1.5×</option><option value="2">2×</option></select></div>}

createRoot(document.getElementById('root')!).render(<App />)
