import { randomUUID } from 'crypto'
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { app, BrowserWindow, net, safeStorage, type WebContentsWillNavigateEventParams } from 'electron'
import type { BaiduAuthStatus } from '../shared/ipc'
import { fetchWithElectronNet, isAsciiHeaderValue } from './media-net'
interface Token { accessToken:string; expiresIn:number; refreshToken:string|null; scope:string|null; receivedAt:number }
const authEndpoint='https://openapi.baidu.com/oauth/2.0/authorize', tokenEndpoint='https://openapi.baidu.com/oauth/2.0/token', downloadEndpoint='https://d.pcs.baidu.com/rest/2.0/pcs/file'
function config(){ const clientId=process.env.BAIDU_CLIENT_ID?.trim(), clientSecret=process.env.BAIDU_CLIENT_SECRET?.trim(), redirectUri=process.env.BAIDU_REDIRECT_URI?.trim(); if(!clientId||!clientSecret||!redirectUri)return null; try{new URL(redirectUri)}catch{return null}; return {clientId,clientSecret,redirectUri,scope:process.env.BAIDU_SCOPE?.trim()||'basic,netdisk'} }
export class BaiduService {
 private readonly config=config(); private token:Token|null|undefined
 async getStatus():Promise<BaiduAuthStatus>{ if(!this.config)return {configured:false,connected:false,expiresAt:null}; try{const t=await this.valid(); return {configured:true,connected:true,expiresAt:t.receivedAt+t.expiresIn*1000}}catch{return {configured:true,connected:false,expiresAt:null}} }
 async login(parent:BrowserWindow|null):Promise<BaiduAuthStatus>{ const c=this.require(); const state=randomUUID(); const url=new URL(authEndpoint); url.search=new URLSearchParams({response_type:'code',client_id:c.clientId,redirect_uri:c.redirectUri,scope:c.scope,state,display:'popup'}).toString(); const code=await this.authWindow(url,state,parent); this.token=await this.exchange({grant_type:'authorization_code',code,redirect_uri:c.redirectUri}); this.save(this.token); return this.getStatus() }
 async logout():Promise<BaiduAuthStatus>{this.token=null; if(existsSync(this.path))rmSync(this.path); return {configured:this.config!==null,connected:false,expiresAt:null}}
 async stream(path:string,request:Request):Promise<Response>{const t=await this.valid(); const u=new URL(downloadEndpoint);u.search=new URLSearchParams({method:'download',access_token:t.accessToken,path}).toString(); const range=request.headers.get('Range'); const headers:Record<string,string>={'User-Agent':'pan.baidu.com'};if(range&&isAsciiHeaderValue(range))headers.Range=range;return fetchWithElectronNet(u.toString(),headers)}
 private require(){if(!this.config)throw new Error('缺少百度 OAuth 配置，请设置 BAIDU_CLIENT_ID、BAIDU_CLIENT_SECRET 和 BAIDU_REDIRECT_URI。');return this.config}
 private authWindow(url:URL,state:string,parent:BrowserWindow|null):Promise<string>{const redirect=new URL(this.require().redirectUri);const win=new BrowserWindow({width:520,height:680,parent:parent??undefined,modal:parent!==null,show:false,title:'登录百度网盘',webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true}});win.setMenuBarVisibility(false);win.once('ready-to-show',()=>win.show()); return new Promise((resolve,reject)=>{let done=false;const finish=(error?:Error,code?:string)=>{if(done)return;done=true;if(!win.isDestroyed())win.destroy();error?reject(error):resolve(code!)};const inspect=(event:Electron.Event<WebContentsWillNavigateEventParams>,candidate:string)=>{let callback:URL;try{callback=new URL(candidate)}catch{return}if(callback.protocol!==redirect.protocol||callback.host!==redirect.host||callback.pathname!==redirect.pathname)return;event.preventDefault();if(callback.searchParams.get('state')!==state)return finish(new Error('百度登录状态校验失败，请重试。'));const error=callback.searchParams.get('error_description')??callback.searchParams.get('error');if(error)return finish(new Error(`百度登录失败：${error}`));const code=callback.searchParams.get('code');return code?finish(undefined,code):finish(new Error('百度登录未返回授权码。'))};win.webContents.on('will-redirect',inspect);win.webContents.on('will-navigate',inspect);win.once('closed',()=>{if(!done)finish(new Error('已取消百度登录。'))});void win.loadURL(url.toString()).catch(e=>finish(new Error(`无法打开百度登录页：${String(e)}`)))}) }
 private async exchange(parameters:Record<string,string>):Promise<Token>{const c=this.require();const response=await net.fetch(tokenEndpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded; charset=utf-8'},body:new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,...parameters})});const p=await response.json() as {access_token?:string;expires_in?:number;refresh_token?:string;scope?:string;error?:string;error_description?:string};if(!response.ok||!p.access_token||typeof p.expires_in!=='number')throw new Error(p.error_description??p.error??`百度 token 请求失败（HTTP ${response.status}）`);return {accessToken:p.access_token,expiresIn:p.expires_in,refreshToken:p.refresh_token??null,scope:p.scope??null,receivedAt:Date.now()} }
 private async valid():Promise<Token>{if(this.token===undefined)this.token=this.load();if(!this.token)throw new Error('尚未登录百度网盘。');if(Date.now()<this.token.receivedAt+this.token.expiresIn*1000-60000)return this.token;if(!this.token.refreshToken){await this.logout();throw new Error('百度登录已过期，请重新登录。')}try{this.token=await this.exchange({grant_type:'refresh_token',refresh_token:this.token.refreshToken});this.save(this.token);return this.token}catch(e){await this.logout();throw e}}
 private get path(){return join(app.getPath('userData'),'credentials','baidu-token.json')}
 private load():Token|null{if(existsSync(this.path)){try{return JSON.parse(readFileSync(this.path,'utf8')) as Token}catch{rmSync(this.path,{force:true})}}const bin=this.path.replace(/\.json$/,'.bin');if(existsSync(bin)&&safeStorage.isEncryptionAvailable()){try{const t=JSON.parse(safeStorage.decryptString(readFileSync(bin))) as Token;this.save(t);rmSync(bin,{force:true});return t}catch{rmSync(bin,{force:true})}}return null}
 private save(token:Token){mkdirSync(dirname(this.path),{recursive:true});writeFileSync(this.path,JSON.stringify(token),{mode:0o600})}
}
