import { app, BrowserWindow, ipcMain, net, protocol } from 'electron'
import { existsSync } from 'fs'
import { readFile } from 'fs/promises'
import { dirname, extname, join, sep } from 'path'
import { IPC_CHANNELS, UPDATE_STATE_CHANNEL, type PlaybackState } from '../shared/ipc'
import { BaiduService } from './baidu'
import { LibraryService } from './library'
import { SOURCE_DB, SnapshotDatabase } from './library-db'
import { initUpdater, getUpdateState, checkForUpdatesNow, installUpdate, onUpdateState } from './updater'
import { startCliServer, stopCliServer, setPlaybackState, ackRemoteCommand } from './cli-server'
import { persistPlaybackState } from './playback-writeback'
import { getConfig, submitSummary, pollJob, fetchResult, startPolling } from './remote-jobs'
import { makeSummaryPrompts, parseSummaryResponse } from './summary-prompt'
import { writeTrackSummary } from './summary-writeback'

protocol.registerSchemesAsPrivileged([
  { scheme:'hb-media', privileges:{standard:true,secure:true,supportFetchAPI:true,stream:true,corsEnabled:true} },
  { scheme:'hb-cover', privileges:{standard:true,secure:true,supportFetchAPI:true,corsEnabled:true} }
])
app.setName('PolarBear')
// 降低显存/峰值内存：本机内存长期吃紧时 GPU 进程过大常导致 network service 被系统终止，播放挂起
app.disableHardwareAcceleration()
let mainWindow:BrowserWindow|null=null
let library:LibraryService
const snapshot = new SnapshotDatabase()
const baidu = new BaiduService()
function createWindow(){ mainWindow=new BrowserWindow({width:1200,height:800,minWidth:900,minHeight:600,backgroundColor:'#141518',titleBarStyle:'hiddenInset',webPreferences:{preload:join(__dirname,'../preload/index.js'),contextIsolation:true,nodeIntegration:false,sandbox:true,spellcheck:false}});mainWindow.on('closed',()=>{mainWindow=null});mainWindow.on('focus',()=>snapshot.refresh(false));if(process.env.ELECTRON_RENDERER_URL)void mainWindow.loadURL(process.env.ELECTRON_RENDERER_URL);else void mainWindow.loadFile(join(__dirname,'../renderer/index.html')) }
function registerIpc(){
 ipcMain.handle(IPC_CHANNELS.getStatus,()=>library.status()); ipcMain.handle(IPC_CHANNELS.refresh,()=>library.refresh()); ipcMain.handle(IPC_CHANNELS.getFolders,()=>library.folders()); ipcMain.handle(IPC_CHANNELS.getFavorites,()=>library.favorites()); ipcMain.handle(IPC_CHANNELS.getCollections,(_e,folderId:string|null,includeArchived?:boolean)=>library.collections(folderId,includeArchived)); ipcMain.handle(IPC_CHANNELS.getTracks,(_e,id:string,page?:number,size?:number,includeArchived?:boolean)=>library.tracks(id,page,size,includeArchived===true)); ipcMain.handle(IPC_CHANNELS.getContinue,(_e,limit?:number)=>library.continueListening(limit)); ipcMain.handle(IPC_CHANNELS.search,(_e,q:string,limit?:number)=>library.search(q,limit)); ipcMain.handle(IPC_CHANNELS.getTrackDetail,(_e,id:string)=>library.getTrackDetail(id));ipcMain.handle(IPC_CHANNELS.getTranscript,(_e,id:string,includeFullText?:boolean)=>library.getTranscript(id,includeFullText===true)); ipcMain.handle(IPC_CHANNELS.getText,(_e,id:string)=>library.textContent(id)); ipcMain.handle(IPC_CHANNELS.resolvePlayback,(_e,id:string)=>library.media(id)); ipcMain.handle(IPC_CHANNELS.baiduStatus,()=>baidu.getStatus()); ipcMain.handle(IPC_CHANNELS.baiduLogin,()=>baidu.login(mainWindow)); ipcMain.handle(IPC_CHANNELS.baiduLogout,()=>baidu.logout());ipcMain.handle(IPC_CHANNELS.playbackPushState,(_e,state:PlaybackState)=>{setPlaybackState(state);persistPlaybackState(state)});ipcMain.handle(IPC_CHANNELS.playbackAckCommand,(_e,commandId:string)=>{ackRemoteCommand(commandId)});ipcMain.handle(IPC_CHANNELS.getVersion,()=>app.getVersion());ipcMain.handle(IPC_CHANNELS.updateGetState,()=>getUpdateState());ipcMain.handle(IPC_CHANNELS.updateCheck,()=>checkForUpdatesNow());ipcMain.handle(IPC_CHANNELS.updateInstall,()=>{installUpdate()})
ipcMain.handle(IPC_CHANNELS.summaryConfigured,()=>{const cfg=getConfig();return{configured:!!(cfg.baseUrl&&cfg.token),baseUrl:cfg.baseUrl??'',model:'qwen3-max'}})
ipcMain.handle(IPC_CHANNELS.summaryGenerate,async(_e,trackId:string)=>{const cfg=getConfig();if(!cfg.baseUrl||!cfg.token)throw new Error('未配置 Remote Jobs 凭据。');const detail=library.getTrackDetail(trackId);if(!detail||!detail.transcript)throw new Error('该曲目无完整转录。');const transcript=library.getTranscript(trackId,true);if(!transcript||!transcript.fullText)throw new Error('转录文本为空。');const prompts=makeSummaryPrompts({trackTitle:detail.track.displayName,trackDuration:detail.track.duration,trackAuthor:detail.track.chapter,collectionTitle:detail.collection?.title??null,collectionDescription:detail.collection?.description??null,segments:transcript.segments.map(s=>({startMs:s.startMs,text:s.text}))});const messages=[{role:'system',content:prompts.systemPrompt},{role:'user',content:prompts.userPrompt}];const entry=await submitSummary({trackId,transcriptId:transcript.language,model:'qwen3-max',title:detail.track.displayName,messages});if(entry.status==='auth_failed'||entry.status==='submit_failed')throw new Error(entry.errorMessage??'提交失败');if(!entry.serverJobId)throw new Error('提交失败：服务器未返回 ID。');const polled=await pollJob(entry.serverJobId);let finalText='';if(polled?.status==='succeeded')finalText=await fetchResult(entry.serverJobId);else{const text=await new Promise<string>((resolve,reject)=>{const handle=startPolling(entry.serverJobId!,job=>{if(job?.status==='succeeded'){handle.stop();fetchResult(entry.serverJobId!).then(resolve).catch(reject)}else if(job?.status==='failed'||job?.status==='canceled'){handle.stop();reject(new Error(job.error?.message??`任务 ${job.status}。`))}},()=>{handle.stop();reject(new Error('轮询结束。'))},err=>{handle.stop();reject(err)});setTimeout(()=>{handle.stop();reject(new Error('摘要生成超时。'))},5*60*1000)});finalText=text}
const parsed=parseSummaryResponse(finalText);const summaryRow=library.getSummary(trackId);const existingUpdatedAt=summaryRow?new Date().toISOString():null;writeTrackSummary(SOURCE_DB,{trackId,transcriptId:transcript.language,language:transcript.language,expectedTranscriptUpdatedAt:new Date().toISOString(),expectedSummary:{exists:!!summaryRow,updatedAt:existingUpdatedAt},summaryTitle:parsed.summaryTitle,summaryBody:parsed.summaryBody,keywords:parsed.keywords,mentionedItems:parsed.mentionedItems,suggestedCorrections:parsed.suggestedCorrections,translations:parsed.translations,sections:parsed.sections,modelIdentifier:'qwen3-max',jobId:entry.serverJobId});const refreshed=library.getTrackDetail(trackId);if(!refreshed)throw new Error('摘要已写入，但刷新失败。');return refreshed.summary??{title:null,body:null,keywords:[],sections:[]}})
}
app.whenReady().then(()=>{ initUpdater();library=new LibraryService(snapshot);snapshot.initialize();registerIpc();onUpdateState(s=>{if(mainWindow&&!mainWindow.isDestroyed())mainWindow.webContents.send(UPDATE_STATE_CHANNEL,s)});setInterval(()=>snapshot.refresh(false),30000);startCliServer(library,baidu,()=>{if(mainWindow&&!mainWindow.isDestroyed())return mainWindow;createWindow();return mainWindow&&!mainWindow.isDestroyed()?mainWindow:null});protocol.handle('hb-cover',async request=>{try{const u=new URL(request.url);const relative=decodeURIComponent(u.pathname).replace(/^\/+/, '');const root=dirname(SOURCE_DB);const file=join(root,relative);if(!(file===root||file.startsWith(root+sep))||!existsSync(file))return new Response('Not found',{status:404});const data=await readFile(file);return new Response(new Uint8Array(data),{headers:{'Content-Type':{'jpg':'image/jpeg','jpeg':'image/jpeg','png':'image/png','gif':'image/gif','webp':'image/webp','bmp':'image/bmp'}[extname(file).toLowerCase().replace('.','')]||'application/octet-stream'}})}catch{return new Response('Bad request',{status:400})}});protocol.handle('hb-media',async request=>{try{const id=decodeURIComponent(new URL(request.url).pathname).replace(/^\/+/, '');const source=library.media(id);if(!source)return new Response('Not found',{status:404});if(source.kind==='baidu')return baidu.stream(source.value,request);const url=new URL(source.value);if(!['http:','https:'].includes(url.protocol))return new Response('Unsupported URL',{status:400});if(url.protocol==='http:')url.protocol='https:';const range=request.headers.get('Range');return net.fetch(url.toString(),{headers:range?{Range:range}:{}})}catch(error){return new Response(String(error),{status:502})}});createWindow()})
app.on('window-all-closed',()=>{if(process.platform!=='darwin'){stopCliServer();app.quit()}});app.on('before-quit',()=>{stopCliServer()});app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow()})
