CREATE TABLE IF NOT EXISTS jobs (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL,
    status TEXT NOT NULL,
    progress DOUBLE PRECISION NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    error_code TEXT,
    error_message TEXT,
    input_kind TEXT,
    input_mime TEXT,
    input_size BIGINT,
    input_text TEXT,
    input_url TEXT,
    input_source TEXT,
    input_cookie TEXT,
    input_path TEXT,
    params_json TEXT,
    output_kind TEXT,
    output_mime TEXT,
    output_size BIGINT,
    output_text TEXT,
    result_path TEXT
);
